package com.itheima.crm;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2018-11-30T17:14:52.844+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://service.itheima.com/", name = "ICustomerService")
@XmlSeeAlso({})
public interface ICustomerService {

    @WebMethod
    @RequestWrapper(localName = "findListNotAssociation", targetNamespace = "http://service.itheima.com/", className = "com.itheima.crm.FindListNotAssociation")
    @ResponseWrapper(localName = "findListNotAssociationResponse", targetNamespace = "http://service.itheima.com/", className = "com.itheima.crm.FindListNotAssociationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.itheima.crm.Customer> findListNotAssociation();

    @WebMethod
    @RequestWrapper(localName = "findCustomerByTelephone", targetNamespace = "http://service.itheima.com/", className = "com.itheima.crm.FindCustomerByTelephone")
    @ResponseWrapper(localName = "findCustomerByTelephoneResponse", targetNamespace = "http://service.itheima.com/", className = "com.itheima.crm.FindCustomerByTelephoneResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.itheima.crm.Customer findCustomerByTelephone(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "assigncustomerstodecidedzone", targetNamespace = "http://service.itheima.com/", className = "com.itheima.crm.Assigncustomerstodecidedzone")
    @ResponseWrapper(localName = "assigncustomerstodecidedzoneResponse", targetNamespace = "http://service.itheima.com/", className = "com.itheima.crm.AssigncustomerstodecidedzoneResponse")
    public void assigncustomerstodecidedzone(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.util.List<java.lang.Integer> arg1
    );

    @WebMethod
    @RequestWrapper(localName = "findDecidedzoneIdByAddress", targetNamespace = "http://service.itheima.com/", className = "com.itheima.crm.FindDecidedzoneIdByAddress")
    @ResponseWrapper(localName = "findDecidedzoneIdByAddressResponse", targetNamespace = "http://service.itheima.com/", className = "com.itheima.crm.FindDecidedzoneIdByAddressResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String findDecidedzoneIdByAddress(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "findListHasAssociation", targetNamespace = "http://service.itheima.com/", className = "com.itheima.crm.FindListHasAssociation")
    @ResponseWrapper(localName = "findListHasAssociationResponse", targetNamespace = "http://service.itheima.com/", className = "com.itheima.crm.FindListHasAssociationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.itheima.crm.Customer> findListHasAssociation(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "findAll", targetNamespace = "http://service.itheima.com/", className = "com.itheima.crm.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://service.itheima.com/", className = "com.itheima.crm.FindAllResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.itheima.crm.Customer> findAll();
}
